# Generated by Django 5.2.9 on 2025-12-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("project_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                (
                    "technologies",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("java", "Java"),
                            ("csharp", "C#"),
                            ("ruby", "Ruby"),
                            ("go", "Go"),
                            ("php", "PHP"),
                            ("typescript", "TypeScript"),
                            ("swift", "Swift"),
                            ("kotlin", "Kotlin"),
                            ("django", "Django"),
                            ("react", "React"),
                            ("angular", "Angular"),
                            ("vue", "Vue.js"),
                            ("flask", "Flask"),
                            ("spring", "Spring"),
                            ("laravel", "Laravel"),
                            ("ruby_on_rails", "Ruby on Rails"),
                            ("express", "Express.js"),
                            ("flutter", "Flutter"),
                            ("nuxt", "Nuxt.js"),
                        ],
                        max_length=255,
                    ),
                ),
                ("date", models.DateField()),
                ("featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "gallery",
                    models.ManyToManyField(
                        blank=True,
                        related_name="project_gallery",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-date"],
            },
        ),
    ]
