# Generated by Django 5.2.9 on 2025-12-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="e.g., devicon class or emoji",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Technologies",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="technologies",
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="projects.technology"
            ),
        ),
    ]
