# Generated by Django 5.2.9 on 2025-12-14 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_category_blogpage_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="categories",
        ),
        migrations.AddField(
            model_name="blogpage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog.category",
            ),
        ),
    ]
