# Generated by Django 5.2.9 on 2025-12-16 04:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_blogpage_categories_blogpage_category"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.CharField(blank=True, max_length=250)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 2),
                    ("code", 5),
                    ("quote", 6),
                    ("video", 10),
                    ("file", 11),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("py", "Python"),
                                ("hs", "JavaScript"),
                                ("html", "HTML"),
                                ("css", "CSS"),
                                ("java", "Java"),
                                ("csharp", "C#"),
                                ("cpp", "C++"),
                                ("ruby", "Ruby"),
                                ("go", "Go"),
                                ("php", "PHP"),
                                ("swift", "Swift"),
                                ("kotlin", "Kotlin"),
                            ]
                        },
                    ),
                    4: ("wagtail.blocks.TextBlock", (), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 3), ("code", 4)]],
                        {"form_classname": "textarea"},
                    ),
                    6: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "YouTube or Vimeo URL"},
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 7), ("caption", 8), ("autoplay", 9)]],
                        {},
                    ),
                    11: ("wagtail.documents.blocks.DocumentChooserBlock", (), {}),
                },
            ),
        ),
    ]
