# Generated by Django 5.2.9 on 2026-01-28 22:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blogpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 3),
                    ("image", 4),
                    ("code", 7),
                    ("quote", 8),
                    ("video", 12),
                    ("file", 13),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("base", "Base"),
                                ("lg", "Large"),
                                ("xl", "Extra Large"),
                            ],
                            "help_text": "Select the text size",
                        },
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: ("wagtail.blocks.StructBlock", [[("size", 1), ("text", 2)]], {}),
                    4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("py", "Python"),
                                ("hs", "JavaScript"),
                                ("html", "HTML"),
                                ("css", "CSS"),
                                ("java", "Java"),
                                ("csharp", "C#"),
                                ("cpp", "C++"),
                                ("ruby", "Ruby"),
                                ("go", "Go"),
                                ("php", "PHP"),
                                ("swift", "Swift"),
                                ("kotlin", "Kotlin"),
                            ]
                        },
                    ),
                    6: ("wagtail.blocks.TextBlock", (), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 5), ("code", 6)]],
                        {"form_classname": "textarea"},
                    ),
                    8: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "YouTube or Vimeo URL"},
                    ),
                    10: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("video_url", 9), ("caption", 10), ("autoplay", 11)]],
                        {},
                    ),
                    13: ("wagtail.documents.blocks.DocumentChooserBlock", (), {}),
                },
            ),
        ),
    ]
