# Generated by Django 5.2.9 on 2026-08-20 19:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 3), ('image', 4), ('pull_quote', 7), ('code', 9), ('quote', 10), ('video', 14), ('file', 15)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Small'), ('base', 'Base'), ('lg', 'Large'), ('xl', 'Extra Large')], 'help_text': 'Select the text size'}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('size', 1), ('text', 2)]], {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.blocks.TextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('author', 5), ('source', 6)]], {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('py', 'Python'), ('js', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('java', 'Java'), ('csharp', 'C#'), ('cpp', 'C++'), ('ruby', 'Ruby'), ('go', 'Go'), ('php', 'PHP'), ('swift', 'Swift'), ('kotlin', 'Kotlin')]}), 9: ('wagtail.blocks.StructBlock', [[('language', 8), ('code', 6)]], {'form_classname': 'textarea'}), 10: ('wagtail.blocks.BlockQuoteBlock', (), {}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube or Vimeo URL'}), 12: ('wagtail.blocks.CharBlock', (), {'required': False}), 13: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('video_url', 11), ('caption', 12), ('autoplay', 13)]], {}), 15: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})}),
        ),
    ]
