# Generated by Django 5.2.9 on 2025-12-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="education",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="homepage",
            name="open_to_work",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="homepage",
            name="pronouns",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="tagline",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
